import type {
	ExportedHandler,
	ExecutionContext,
	Fetcher,
	ScheduledController
} from '@cloudflare/workers-types';
// Generated by `vite build` via @sveltejs/adapter-cloudflare. The file only exists
// after a build has run, so we suppress the resolution error here.
// @ts-ignore — build artifact
import sveltekit from '../.svelte-kit/cloudflare/_worker.js';
import { runCron, type CronEnv } from '$lib/server/cron';

type Env = CronEnv & { ASSETS: Fetcher };

export default {
	fetch(request, env, ctx) {
		return sveltekit.fetch(request, env, ctx);
	},
	scheduled(_event: ScheduledController, env, ctx: ExecutionContext) {
		ctx.waitUntil(
			runCron(env).then((r) => console.log('cron run:', JSON.stringify(r)))
		);
	}
} satisfies ExportedHandler<Env>;
